package pl.lewandowski.youtubesummary;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

@Service
public class PdfReportService {

    public void generatePdf() throws IOException {
        Document document = new Document();
        YtChatResponse ytChatResponse = new YtChatResponse("Summary", "Homework");
        try {
            //tworzymy dokument pdf i zapisujemy go w pliku Raport.pdf
            PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));
            document.open();
            //IMAGE
            addImage(document);
            //SUMMARY
            addSummary(document, ytChatResponse);
            //HOMEWORK
            addHomework(document, ytChatResponse);
            //FOOTER
            addFooter(document);

            //przed wygenerowaniem raportu trzeba zamknac dokument
            document.close();


        } catch (DocumentException e) {
            throw new RuntimeException(e);
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }

    }

    public void addFooter(Document document) throws DocumentException {
        Paragraph footer = new Paragraph();
        Font font = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.STRIKETHRU);
        footer.add(new Paragraph("Generated by Peter", font));
        footer.setAlignment(Element.ALIGN_RIGHT);
        document.add(footer);
    }


    public void addImage(Document document) throws IOException, DocumentException {
        Image logo = Image.getInstance("src/main/resources/static/images/javaicon.png");
        logo.scalePercent(20, 20);
        logo.setAlignment(Element.ALIGN_RIGHT);
        document.add(logo);
    }

    public void addSummary(Document document, YtChatResponse ytChatResponse) throws DocumentException {
        Paragraph header = new Paragraph();
        Font font = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLDITALIC);
        header.add(new Paragraph("Summary of material: ", font));
        header.setAlignment(Element.ALIGN_TOP);
        document.add(header);
        document.add(new Paragraph(ytChatResponse.summary()));
    }

    public void addHomework(Document document, YtChatResponse ytChatResponse) throws DocumentException {
        Paragraph header = new Paragraph();
        Font font = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLDITALIC);
        header.add(new Paragraph("Your homework to do: ", font));
        header.setAlignment(Element.ALIGN_TOP);
        document.add(header);
        document.add(new Paragraph(ytChatResponse.homework()));
    }

}
